version: '3.4'

services:
  acc-text-api:
    volumes:
      - ./api/resources/:/opt
      - ./eval/data/document-plans/:/opt/document-plans
  eval:
    build:
      context: eval
      dockerfile: Dockerfile
    environment:
      ACC_TEXT_URL: http://acc-text-api:3001
