version: '3.3'

services:
  dynamodb:
    image: registry.gitlab.com/tokenmill/nlg/accelerated-text/dynamodb-local:latest
    ports: ["8000:8000"]
  s3:
    image: registry.gitlab.com/tokenmill/nlg/accelerated-text/s3-local:latest
    ports: ["8002:8000"]
  legacy-api:
    build:
      context: nlg-api/
      dockerfile: Dockerfile.legacy-rest-api
      args:
        S3_ENDPOINT: http://localhost:8002
        AWS_DEFAULT_REGION: $NLG_AWS_DEFAULT_REGION
        AWS_ACCESS_KEY_ID: $NLG_AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $NLG_AWS_SECRET_ACCESS_KEY
    ports: ["8081:8080"]
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      AWS_ACCESS_KEY_ID: $NLG_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $NLG_AWS_SECRET_ACCESS_KEY
  graphql-api:
    build:
      context: graphql-api/
      dockerfile: Dockerfile.rest-api
    ports: ["3001:3001"]
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      AWS_ACCESS_KEY_ID: $NLG_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $NLG_AWS_SECRET_ACCESS_KEY
