version: '3.3'

services:
  dynamodb:
    image: registry.gitlab.com/tokenmill/nlg/accelerated-text/dynamodb-local:latest
    ports: ["8000:8000"]
  s3:
    image: registry.gitlab.com/tokenmill/nlg/accelerated-text/s3-local:latest
    ports: ["8002:8000"]
  legacy-api:
    build:
      context: .
      dockerfile: nlg-api/Dockerfile.legacy-rest-api
      args:
        S3_ENDPOINT: http://localhost:8002
        AWS_DEFAULT_REGION: $NLG_AWS_DEFAULT_REGION
        AWS_ACCESS_KEY_ID: $NLG_AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $NLG_AWS_SECRET_ACCESS_KEY
    ports: ["8081:8080"]
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      AWS_ACCESS_KEY_ID: $NLG_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $NLG_AWS_SECRET_ACCESS_KEY
  graphql-api:
    build:
      context: .
      dockerfile: graphql-api/Dockerfile.rest-api
    ports: ["3001:3001"]
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      AWS_ACCESS_KEY_ID: $NLG_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $NLG_AWS_SECRET_ACCESS_KEY
  fake-shop:
    build:
      context: fake-shop-lambdas
      dockerfile: Dockerfile
    ports: ["8090:8090"]
    environment:
      API_URL: http://localhost:8090/mock-shop
      PORT: 8090
