#!/bin/sh

if ! [ -x "$(command -v joker)" ]; then
    echo 'No `joker` binary, skipping initial lint.' >&2
    exit 0
fi

git diff --name-status | while read st file; do
    # skip deleted files
    if [ "$st" == 'D' ]; then continue; fi
    # do a check only on the clj files
    if [[ "$file" =~ ".clj" ]]; then
        echo "Linting $file"
        joker --lint $file
        if [ $? -ne 0 ]
        then
            echo "Lint failed"
            exit 1
        fi
    fi
done
