FROM node:11-slim

RUN apt-get update -qq && apt-get install -y -qq build-essential chromium libatk-bridge2.0-0 libgtk-3-0 libnss3

RUN mkdir -p /usr/src/tests
WORKDIR /usr/src/tests

COPY tests/ /usr/src/tests

RUN npm install puppeteer
RUN npm install

CMD ["npm", "run", "bdd"]