FROM registry.gitlab.com/tokenmill/clojure:1 as builder

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app
RUN clojure -Auberjar

FROM openjdk:8u171-jre-alpine3.8
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/target/nlg-api-0.0.1-standalone.jar /usr/src/app
COPY --from=builder /usr/src/app/lib /usr/src/app/lib
CMD ["java", "-cp", "nlg-api-0.0.1-standalone.jar:lib/*", "local_server"]
