FROM registry.gitlab.com/tokenmill/clojure:1

RUN mkdir /root/.gitlibs

ARG AWS_DEFAULT_REGION
ENV AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID

ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

COPY data-access/deps.edn /usr/src/data-access/
WORKDIR /usr/src/data-access
RUN clojure -R:test || true

COPY nlg-api/deps.edn /usr/src/app/
WORKDIR /usr/src/app
RUN clojure -R:test:rest-uberjar || true
