FROM registry.gitlab.com/tokenmill/nlg/accelerated-text/nlg-api:deps

ARG AWS_DEFAULT_REGION
ENV AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID

ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY nlg-api/deps.edn /usr/src/app
COPY nlg-api/src /usr/src/app/src
COPY nlg-api/test /usr/src/app/test
COPY nlg-api/resources /usr/src/app/resources
COPY data-access/ /usr/src/data-access
CMD ["clojure", "-A:test"]
