AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless API - NLG

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  getDocumentPlans:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.DocumentPlansHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans/{id}/variants
            Method: get

  generateText:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg
            Method: post

  deleteNLGresult:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg/{id}
            Method: delete

  getNLGresult:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBReadOnlyAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg/{id}
            Method: get

  NLGCors:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg/{id}
            Method: options

  getWorkspace:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBReadOnlyAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans/{id}
            Method: get

  dpCors:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans/{id}
            Method: options

  listWorkspaces:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBReadOnlyAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans
            Method: get

  addWorkspace:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans
            Method: post

  updateWorkspace:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans/{id}
            Method: put

  deleteWorkspace:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans/{id}
            Method: delete

  dataCors:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /data
            Method: options

  addData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.DataHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /data
            Method: post

  listData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.DataHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBReadOnlyAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /data
            Method: get

  deleteData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.DataHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /data/{id}
            Method: delete

  getData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.DataHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBReadOnlyAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /data/{id}
            Method: get

  searchLexicon:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.LexiconHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBReadOnlyAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /lexicon
            Method: get

  createLexicon:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.LexiconHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /lexicon
            Method: post

  updateLexicon:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.LexiconHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /lexicon
            Method: put

  lexiconCors:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lt.tokenmill.nlg.api.LexiconHandler::handleRequest
      Runtime: java8
      CodeUri: target/uberjar/nlg-api-0.1.0-SNAPSHOT-standalone.jar
      MemorySize: 512
      Timeout: 60
      Policies:
        - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /lexicon
            Method: options

Outputs:
  GetDocumentsPlansAPI:
    Description: URL for document plans
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/document-plans/{id}/variants'
    Export:
      Name: getDocumentPlans

  GetWorkspaceAPI:
    Description: URL to get Workspace
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/document-plans/{id}'
    Export:
      Name: getWorkspace

  ListWorkspacesAPI:
    Description: URL to list Workspaces
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/document-plans'
    Export:
      Name: listWorkspaces

  AddWorkspaceAPI:
    Description: URL to add Workspace
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/document-plans/'
    Export:
      Name: addWorkspace

  UpdateWorkspaceAPI:
    Description: URL to update Workspace
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/document-plans/{id}'
    Export:
      Name: updateWorkspace

  DeleteWorkspaceAPI:
    Description: URL to delete Workspace
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/document-plans/{id}'
    Export:
      Name: deleteWorkspace

  textGenerationAPI:
    Description: URL to generate text
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/nlg'
    Export:
      Name: generateText

  getNLGresultAPI:
    Description: URL to get result
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/nlg/{id}'
    Export:
      Name: getNLGresult

  deleteNLGresultAPI:
    Description: URL to delete result
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/nlg/{id}'
    Export:
      Name: deleteNLGresult

  NLGCorsAPI:
    Description: setup CORS
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/nlg/{id}'
    Export:
      Name: NLGCors

  TextGenCorsAPI:
    Description: setup CORS
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/nlg/'
    Export:
      Name: TextGenCors

  dpCorsAPI:
    Description: setup CORS
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/document-plans/{id}'
    Export:
      Name: dpCors

  addDataAPI:
    Description: add data
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/data'
    Export:
      Name: addData

  getDataAPI:
    Description: get data
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/data/{id}'
    Export:
      Name: getData

  deleteDataAPI:
    Description: delete data
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/data/{id}'
    Export:
      Name: deleteData

  lexiconSearchAPI:
    Description: lexicon search API
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/lexicon/search'
    Export:
      Name: lexiconSearchAPI

  lexiconCreateAPI:
    Description: lexicon create API
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/lexicon/create'
    Export:
      Name: lexiconCreateAPI

  lexiconUpdateAPI:
    Description: lexicon update API
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/lexicon/update'
    Export:
      Name: lexiconUpdateAPI
