AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  graphqlApi:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      Tracing: "Active"
      MemorySize: 3008
      Handler: not.used
      Runtime: provided
      CodeUri: function.zip
      Policies:
        - AWSLambdaExecute
      Environment:
        Variables:
          ENABLE_XRAY: "true"
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /_graphql
            Method: post

  graphqlApiLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${graphqlApi}
      RetentionInDays: 1

Outputs:
  graphqlApiApi:
    Description: GraphQL URI
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/nlg/_graphql'
    Export:
      Name: !Sub ${AWS::StackName}:NLG-API
