AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless API - NLG
Globals:
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''content-type, *'''
      AllowOrigin: '''*'''
Resources:
  getDocumentPlans:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.DocumentPlansHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans/{id}/variants
            Method: get
  generateText:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://dynamodb.eu-central-1.amazonaws.com
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg
            Method: post
  deleteNLGresult:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://dynamodb.eu-central-1.amazonaws.com
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg/{id}
            Method: delete
  getNLGresult:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://dynamodb.eu-central-1.amazonaws.com
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg/{id}
            Method: get
  NLGIdCors:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg/{id}
            Method: options
  NLGCors:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.NLGHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /nlg
            Method: options
  getWorkspace:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://dynamodb.eu-central-1.amazonaws.com
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans/{id}
            Method: get
  dpCors:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans/{id}
            Method: options
  listWorkspaces:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://dynamodb.eu-central-1.amazonaws.com
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans
            Method: get
  addWorkspace:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://dynamodb.eu-central-1.amazonaws.com
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans
            Method: post
  updateWorkspace:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://dynamodb.eu-central-1.amazonaws.com
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans/{id}
            Method: put
  deleteWorkspace:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://dynamodb.eu-central-1.amazonaws.com
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /document-plans/{id}
            Method: delete
  dataCors:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.WorkspaceHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /data
            Method: options
  listData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.DataHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /data
            Method: get
  getData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.DataHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /data/{user}/{file}
            Method: get
  searchLexicon:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.LexiconHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://dynamodb.eu-central-1.amazonaws.com
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /lexicon
            Method: get
  createLexicon:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.LexiconHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://dynamodb.eu-central-1.amazonaws.com
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /lexicon
            Method: post
  lexiconCors:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.LexiconHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /lexicon
            Method: options
  updateIdLexicon:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api.LexiconHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://dynamodb.eu-central-1.amazonaws.com
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /lexicon/{id}
            Method: put
  deleteIdLexicon:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.LexiconHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://dynamodb.eu-central-1.amazonaws.com
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /lexicon/{id}
            Method: delete
  lexiconIdCors:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlg.api.LexiconHandler::handleRequest
      Runtime: java8
      CodeUri: s3://nlg-api/20cae0795e0c718ccc7edc6c103cf6e9
      MemorySize: 3008
      Timeout: 60
      Policies:
      - AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /lexicon/{id}
            Method: options
